obj-y += entry/

obj-$(CONFIG_PERF_EVENTS) += events/

obj-$(CONFIG_KVM) += kvm/

# Xen paravirtualization support
obj-$(CONFIG_XEN) += xen/

# lguest paravirtualization support
obj-$(CONFIG_LGUEST_GUEST) += lguest/

# s-Par paravirtualization support
obj-$(CONFIG_UNISYS_VISORBUS) += visorbus/

obj-y += realmode/
obj-y += kernel/
obj-y += mm/

obj-y += crypto/

obj-$(CONFIG_IA32_EMULATION) += ia32/

obj-y += platform/
obj-y += net/

obj-$(CONFIG_KEXEC_FILE) += purgatory/
